package SpeedClick;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;

import java.util.Timer;
import java.util.TimerTask;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author vedie
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    Grille GrilleJeu = new Grille();
    Joueur JoueurCourant;
    Bouton BoutonJeu[][];
    boolean boutonAllumé;
    static int second = 0;
    static int millisecond = 0;
    int Compteur = 0;
    Timer chronometre = new Timer();

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {

        initComponents();
        panneau_grille.setVisible(false);
        infopartie.setVisible(false);
        info_joueur.setVisible(false); //on rend invisible certains panels tant que le joueur ne click pas sur démarrer.
        scoreJoueur.setText("" + Compteur); //on met un compteur à coté du score du joueur (emplacement scoreJoueur)

        for (int i = 3; i >= 0; i--) {
            for (int j = 0; j <4; j++) {

                CelluleGraphique cellGraph = new CelluleGraphique(GrilleJeu.BoutonJeu[i][j]);
                panneau_grille.add(cellGraph);
                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Bouton B = cellGraph.BoutonAssocie;
                        if (B.BoutonAllumé() == true) {
                            Eteindre(B);
                            Random r = new Random();
                            int ligne_B = r.nextInt(4);
                            int colonne_B = r.nextInt(4);
                            GrilleJeu.AllumerBouton(ligne_B, colonne_B);
                            panneau_grille.repaint();
                        } else {

                        }
                    }
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        infopartie = new javax.swing.JPanel();
        informations = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scoreJoueur = new javax.swing.JLabel();
        chronoJoueur = new javax.swing.JLabel();
        info_joueur = new javax.swing.JPanel();
        meilleur_score = new javax.swing.JLabel();
        nomJoueur = new javax.swing.JLabel();
        pseudoJoueur = new javax.swing.JLabel();
        Début = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Pseudo = new javax.swing.JTextField();
        lancerPartie = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(204, 204, 204));
        panneau_grille.setPreferredSize(new java.awt.Dimension(100, 100));
        panneau_grille.setLayout(new java.awt.GridLayout(4, 4));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 400));

        infopartie.setBackground(new java.awt.Color(102, 153, 255));
        infopartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        informations.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        informations.setText("Informations partie :");
        infopartie.add(informations, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 160, 40));

        jLabel2.setText("Chronomètre :");
        infopartie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setText("Score :");
        infopartie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        scoreJoueur.setText("scoreJoueur");
        infopartie.add(scoreJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        chronoJoueur.setText("chronoJoueur");
        infopartie.add(chronoJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        getContentPane().add(infopartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 230, 240));

        info_joueur.setBackground(new java.awt.Color(0, 153, 204));
        info_joueur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        info_joueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        meilleur_score.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        meilleur_score.setText("Meilleur score :");
        info_joueur.add(meilleur_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        nomJoueur.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        nomJoueur.setText("Nom du joueur :");
        info_joueur.add(nomJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        pseudoJoueur.setText("pseudoJoueur");
        info_joueur.add(pseudoJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        getContentPane().add(info_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 230, 135));

        Début.setBackground(new java.awt.Color(204, 204, 255));
        Début.setForeground(new java.awt.Color(204, 204, 255));
        Début.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel4.setText("Votre pseudo :");
        Début.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 130, 50));

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 36)); // NOI18N
        jLabel5.setText("SPEED CLICK");
        Début.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 360, 90));

        Pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PseudoActionPerformed(evt);
            }
        });
        Début.add(Pseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, 40));

        lancerPartie.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        lancerPartie.setText("Démarrer");
        lancerPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancerPartieActionPerformed(evt);
            }
        });
        Début.add(lancerPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 160, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel1.setText("Mayeul Kaeppelin");
        Début.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel6.setText("Manon Védie");
        Début.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 70, 20));

        getContentPane().add(Début, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 530, 330));

        setBounds(0, 0, 789, 491);
    }// </editor-fold>//GEN-END:initComponents

    private void PseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PseudoActionPerformed

    private void lancerPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancerPartieActionPerformed
        // TODO add your handling code here:
        panneau_grille.setVisible(true); //On rend visible les panels de jeu
        infopartie.setVisible(true);
        info_joueur.setVisible(true);
        Début.setVisible(false); //on met invisible la page d'accueil

        initialiserPartie();
        boolean chrono = false;
        chrono = chronometre();
    }//GEN-LAST:event_lancerPartieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    public void initialiserPartie() {

        //GrilleJeu.eteindreGrille(); //on eteint toute la grille avant chaque début de partie
        //Scanner sc= new Scanner(System.in);
        //System.out.print("Pseudo: "); //on demande au joueur de rentrer son nom
        String nom_J = Pseudo.getText();
        Joueur J = new Joueur(nom_J);
        JoueurCourant = J;

        pseudoJoueur.setText(nom_J);

        Random r = new Random();
        int lig1 = r.nextInt(4); //on choisit un nb entre 1 et 4 pour définir le bouton qui va s'allumer dès le début
        int col1 = r.nextInt(4);
        GrilleJeu.AllumerBouton(lig1, col1); //des le début, on aura un de nos boutons allumé.
        panneau_grille.repaint();// permet de rafraichir l'écran afin de pouvoir jouer normalement. si l'on ne l'utilise pas il faut passer sur les cases a la souris afin de voir les jetons s'afficher

    }

    public void Grille() {
        BoutonJeu = new Bouton[4][4]; //on crée notre première grille de jeu
        for (int i = 0; i < 4; i++) { // Bouton[0][0] en bas à gauche
            for (int j = 0; j < 4; j++) {
                BoutonJeu[i][j] = new Bouton(); // dimensions 4x4
            }
        }
    }

    public void eteindreGrille() { //on eteint tous les boutons de la grille
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                BoutonJeu[i][j].Couleur = "noir";
            }
        }
    }

    public void FinPartie() {
        for (int i = 3; i >= 0; i--) {
            for (int j = 0; j < 4; j++) {
                GrilleJeu.eteindreGrille();
                panneau_grille.repaint();

            }
        }
    }

    public boolean chronometre() {
        Timer chrono = new Timer();
        chrono.schedule(new TimerTask() {
            int time = 20;

            @Override
            public void run() {
                chronoJoueur.setText("" + time);
                if (time == 0) {
                    FinPartie();
                    cancel();// stoppe le chrono au bout de 20 s
                }
                time--;
            }
        }, 1000, 1000);
        return true;
    }

    public boolean Allumé(Bouton boutonCourant) {
        if (boutonCourant.BoutonAllumé() == true) {
            return false;
        } else {
            boutonAllumé = true; //on allume le bouton s'il ne l'est pas déjà
            return true;
        }

    }

    public boolean Eteindre(Bouton boutonCourant) {
        if (boutonCourant.BoutonAllumé() == false) {
            return true;
        } else {
            boutonCourant.boutonAllumé = false; //on eteint le bouton s'il ne l'est pas déjà
            Compteur++;
            scoreJoueur.setText("" + Compteur);
            panneau_grille.repaint();
            return false;
        }

    }

    public boolean BoutonAllumé() { //on demande si le bouton est déjà allumé ou non
        return boutonAllumé;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Début;
    private javax.swing.JTextField Pseudo;
    private javax.swing.JLabel chronoJoueur;
    private javax.swing.JPanel info_joueur;
    private javax.swing.JPanel infopartie;
    private javax.swing.JLabel informations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton lancerPartie;
    private javax.swing.JLabel meilleur_score;
    private javax.swing.JLabel nomJoueur;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JLabel pseudoJoueur;
    private javax.swing.JLabel scoreJoueur;
    // End of variables declaration//GEN-END:variables
}
